### PR TITLE
zen-observable implementation in Typescript to remove import issues

### LINKED ISSUE #389: zen-observable breaks while compiling.
**Intended outcome:**

I updated the apollo-client and added apollo-link to my React-Native app. But the apollo-link breaks during compiling phase, but I expected the app to run smoothly as I have already updated the same in another react app.

react-native version : 0.49.1
apollo-link version: 1.0.7

**Code for apollo Client**

```
import { ApolloClient } from 'apollo-client'
import { HttpLink, createHttpLink } from 'apollo-link-http';
import { setContext } from 'apollo-link-context';
import { InMemoryCache, IntrospectionFragmentMatcher } from 'apollo-cache-inmemory';
import schema from './schema.json'

const httpLink = createHttpLink({ uri: `localhost:3000/graphql` });

const cache = new InMemoryCache({
  fragmentMatcher: new IntrospectionFragmentMatcher({
    introspectionQueryResultData: schema.data
  }),
});

const client = new ApolloClient({
  link: httpLink,
  cache: cache,
});

export default client

```
**Actual outcome:**
screen shot 2018-01-05 at 8 32 41 pm

```
error: bundling failed: TypeError: pathToNodeModules/node_modules/zen-observable/zen-observable.js: Property left of AssignmentExpression expected node to be of a type ["LVal"] but instead got "ConditionalExpression"
    at Object.validate (pathToNodeModules/node_modules/babel-types/lib/definitions/index.js:109:13)
    at Object.validate (pathToNodeModules/node_modules/babel-types/lib/index.js:505:9)
    at NodePath._replaceWith (pathToNodeModules/node_modules/babel-traverse/lib/path/replacement.js:176:7)
    at NodePath.replaceWith (pathToNodeModules/node_modules/babel-traverse/lib/path/replacement.js:160:8)
    at PluginPass.MemberExpression (pathToNodeModules/node_modules/babel-preset-react-native/transforms/transform-symbol-member.js:33:14)
    at newFn (pathToNodeModules/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (pathToNodeModules/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (pathToNodeModules/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (pathToNodeModules/node_modules/babel-traverse/lib/path/context.js:105:12)
error: bundling failed: TypeError: pathToNodeModules/node_modules/zen-observable/zen-observable.js: Property left of AssignmentExpression expected node to be of a type ["LVal"] but instead got "ConditionalExpression"
    at Object.validate (pathToNodeModules/node_modules/babel-types/lib/definitions/index.js:109:13)
    at Object.validate (pathToNodeModules/node_modules/babel-types/lib/index.js:505:9)
    at NodePath._replaceWith (pathToNodeModules/node_modules/babel-traverse/lib/path/replacement.js:176:7)
    at NodePath.replaceWith (pathToNodeModules/node_modules/babel-traverse/lib/path/replacement.js:160:8)
    at PluginPass.MemberExpression (pathToNodeModules/node_modules/babel-preset-react-native/transforms/transform-symbol-member.js:33:14)
    at newFn (pathToNodeModules/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (pathToNodeModules/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (pathToNodeModules/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (pathToNodeModules/node_modules/babel-traverse/lib/path/context.js:105:12)
  
  
```

### LINKED ISSUE #476: "TypeError: forward(...).flatMap is not a function" with apollo-link 1.1.0.
Hey guys!

We've got a custom middleware that takes a mutation operation and keeps it in a queue for an undetermined amount of time. The use-case is a CQRS-style task-based command API where confirmations are received asynchronously through a websocket, instead of "synchronously" as mutation response. The code looks something like this:

```js
return forward(operation).flatMap(response =>
  new Observable(observer => {
    putInQueueUntilWeReceiveConfirmation(response).then(observer.next).then(observer.complete);
  })
);
```

Up until `1.0.7` this worked fine, however, starting from `1.1.0` this is throwing a `TypeError: forward(...).flatMap is not a function` exception. Did anything change with the way operation observables are passed? I can't seem to find anything in the changelog.

Downgrading `apollo-link` to `1.0.7` fixes this issue, so it is definitely introduced in `1.1.0`.

### LINKED ISSUE #511: Error when building with v1.2.0: "@types/zen-observable/index has no default export"
**Intended outcome:**

Build Angular CLI project with apollo-link. Looks like the latest release has issues with types/zen-observable

**Actual outcome:**

Got this error: 

```bash
ERROR in node_modules/apollo-link-context/node_modules/apollo-link/lib/types.d.ts(2,8): error
TS1192: Module '"/tmp/build_6e1e79a9d4e4cc0fceeda16a93512a8c/node_modules/@types/zen
observable/index"' has no default export.
```

**How to reproduce the issue:**

Typical Angular CLI setup with apollo-client v2.2.5 and apollo-angular v1.0.1. Only happens with apollo-link v1.2.0

### PR DESCRIPTION
**Pull request by evans**
We need an implementation of zen-observable in typescript, since importing the current `zen-observable` library breaks when this library and apollo-client are imported. `* as Observable` imports break js builds(#248) and a direct import necessitates the `allowSyntheticDefaultImports` in users `tsconfig.json`s(#511). [This comment](https://github.com/apollographql/apollo-link/pull/457#issuecomment-364169732) suggests we could use `import Observable = require('zen-observable')`, however it requires emitting as a non-ES module, such as CJS.

This PR contains a typescript wrapper around a `require`d zen-observable, since the wrapper allows us to import zen observable in an interoperable way and gain the typings.

The ultimate goal is to move to RxJs(#380) due to its stability and the extensiveness of its operators. The main concern was the bundle size. With Lettable operators this is no longer a concern.

Fixes #476 Fixes #511 Fixes #389

### CODE REVIEW

**Comment by evans** [comment]
This solution is definitely non-ideal, since it requires maintaining another implementation of zen-observable. If there is a better way forward, please let me know

**Comment by evans** [comment]
@benjamn pointed out that we can import `zen-observable` with a `require` interoperable, so since we already have the types written, we area able to depend on the logic of the zen-observable package. 

This solution seems like the best way to go, since it removes the need to reimplement and we have typing information.

I still have questions about interoperability with other zen-observable's, such as will `instanceof` and symbols still work.

File: packages/zen-observable-ts/src/zenObservable.ts [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+
+import { ZenObservable } from './types';
+
+export { ZenObservable };
+
+export type Observer<T> = ZenObservable.Observer<T>;
+export type Subscriber<T> = ZenObservable.Subscriber<T>;
+export type ObservableLike<T> = ZenObservable.ObservableLike<T>;
+
+export default class Observable<T> {
```
Comment (benjamn) [inline packages/zen-observable-ts/src/zenObservable.ts]: Since you mentioned `instanceof`, it might be possible to make this class inherit from `_Observable`:
```typescript
export default class Observable<t> extends _Observable {
```

File: packages/zen-observable-ts/src/zenObservable.ts [hunk 2]
```diff
@@ -0,0 +1,69 @@
...
+  public subscribe(
+    observerOrNext: ((value: T) => void) | ZenObservable.Observer<T>,
+    error?: (error: any) => void,
+    complete?: () => void,
+  ): ZenObservable.Subscription {
+    return this.observable.subscribe(observerOrNext, error, complete);
+  }
+
+  public forEach(fn: (value: T) => void): Promise<void> {
+    return this.observable.forEach(fn);
```
Comment (benjamn) [inline packages/zen-observable-ts/src/zenObservable.ts]: If `Observable<T>` extends `_Observable`, then methods implementations like this would become
```typescript
return super.forEach(fn);
```
because `this instanceof _Observable`.

File: packages/zen-observable-ts/src/zenObservable.ts [hunk 3]
```diff
@@ -0,0 +1,69 @@
...
+  ): Observable<R> {
+    return _Observable.from(observable);
+  }
+
+  public static of<R>(...items: R[]): Observable<R> {
+    return _Observable.of(...items);
+  }
+
+  constructor(subscriber: ZenObservable.Subscriber<T>) {
+    this.observable = new _Observable(subscriber);
```
Comment (benjamn) [inline packages/zen-observable-ts/src/zenObservable.ts]: And here you would just call `super(subscriber)`.

File: packages/zen-observable-ts/src/zenObservable.ts (hunk 1 above)
Comment (evans) [reply packages/zen-observable-ts/src/zenObservable.ts]: Looks like `extend _Observable` causes [ts] 'extends' clause of exported class 'Observable' has or is using private name '_Observable'. I'm not overly worried about this change, since it is an implementation detail that leaks out and `instanceof` will still  work within the `apollo-link`'s exported observable
